# Generated by Django 2.2.19 on 2023-04-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230401_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
    ]
