# Generated by Django 2.2.19 on 2023-03-09 10:47

import csv
import os

from django.conf import settings
from django.db import migrations


def add_data(apps, schema_editor):
    Ingredients = apps.get_model('recipes', 'Ingredients')
    with open('/Users/lkaydalov/Dev/foodgram-project-react/data/ingredients.csv') as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='"')
        for row in reader:
            name, measurement_unit = row
            Ingredients.objects.create(name=name, measurement_unit=measurement_unit)

def remove_data(apps, schema_editor):
    Ingredients = apps.get_model('recipes', 'Ingredients')
    Ingredients.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230309_1045'),
    ]

    operations = [
        migrations.RunPython(
        add_data,
        remove_data,
    ),
    ]
