# Generated by Django 2.2.19 on 2023-03-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230311_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='is_in_shopping_cart',
        ),
    ]
