# Generated by Django 2.2.19 on 2023-03-27 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230317_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouriterecipe',
            options={'verbose_name': 'Избранный рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterField(
            model_name='ingredientsrecipe',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterUniqueTogether(
            name='favouriterecipe',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcartrecipe',
            unique_together=set(),
        ),
    ]
