# Generated by Django 2.2.19 on 2023-03-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230330_1444'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcartrecipe',
            name='unique_user_recipe',
        ),
    ]
